project:
  type: website
  output-dir: docs

website:
  title: "Computational Physics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - setup.qmd
  sidebar:
    style: "docked"
    search: true
    contents:

      - section: "Getting Started"
        contents:
          - markdown/recap.qmd
          - markdown/quality.qmd
          - markdown/recap_questions.qmd
      - section: "Getting Results"
        contents:
          - section: "Integrals"
            contents:
              - href: markdown/integration_introduction.qmd
                text: Introduction
              - notebooks/integration.ipynb
              - notebooks/monte_carlo.ipynb
              - href: markdown/integration_questions.qmd
                text: Questions
          - section: "Derivatives"
            contents:
              - href: markdown/differentiation_introduction.qmd
                text: Introduction
              - notebooks/finite_difference.ipynb
              - notebooks/error_accuracy_speed.ipynb
              - href: markdown/differentiation_questions.qmd
                text: Questions
          - section: "Ordinary Differential Equations"
            contents:
             - href: markdown/ODE_introduction.qmd
               text: Introduction
             - notebooks/ODE_classification.ipynb
             - notebooks/ODE_boundary_and_initial.ipynb
             - notebooks/euler_method.ipynb
             - notebooks/runge_kutta_method.ipynb
             - notebooks/multivariable_equations.ipynb
             - href: markdown/ODE_questions.qmd
               text: Questions
          - section: "Partial Differential Equations"
            contents:
             - href: markdown/PDE_introduction.qmd
               text: Introduction
             - notebooks/PDE_classification.ipynb
             - notebooks/PDE_boundary_and_initial.ipynb
             - notebooks/relaxation_method.ipynb
             - notebooks/FTCS_method.ipynb
             - href: markdown/PDE_questions.qmd
               text: Questions
          - href: notebooks/problem_solving.ipynb
            text: Problem Solving
      - section: "Getting It Out There"
        contents:
          - href: markdown/out_there_introduction.qmd
            text: Introduction
          - href: markdown/scripting.qmd
            text: Scripting
          - href: markdown/websites.qmd
            text: Build-your-own Website
          - href: markdown/version_control.qmd
            text: Version Control
          - href: markdown/documentation.qmd
            text: Documentation
          - href: markdown/testing.qmd
            text: Testing

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



