---
title: "About"
---

This website contains resources for the second year course "Theory, computation and experiment" (KD5081) at Northumbria University, UK. The resources have been developed by [Dr Lucy Whalley](https://lucydot.github.io). If you spot any mistakes or have any suggestions please [raise an issue](https://github.com/NU-CEM/Computational_Physics/issues) on the Github repository for this course.

The website is powered by [Github](https://github.com/NU-CEM/CompPhys/) and [fastpages](https://github.com/fastai/fastpages), which is licensed under [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0.txt).

The content of this website is adapted and derived from several other sources:

- The Setup instructions page is a derivative of materials from [Software Carpentry](https://software-carpentry.org/), used under [Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/).
- The tutorial "Testing and Documentation" is a derivative of the [Testing lesson from Code Refinery](https://coderefinery.github.io/testing/motivation/"), used under [Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/). 
- Some of the exercises are adapted from the book [Computational Physics](http://www-personal.umich.edu/~mejn/cp/). These are used with the permission of the book's author, Mark Newman, and remain under his copyright. 

In addition, parts of the "Getting results" section were inspired by [Rudolf Winter's notes on ODEs and PDEs](https://users.aber.ac.uk/ruw/teach/260/).

The content of this website unless otherwise indicated is licensed under [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/). You can re-use any of its content as long as an attribution is included, and you indicate if changes were made.
