---
title: "Setup"
---

To participate in this course you will need access to [Python](https://www.python.org/) and an up-to-date web browser. You will also need a range of Python libraries from the standard scientific stack: Jupyter, Numpy, Scipy and Matplotlib.

All of the software needed for this course is pre-installed in the MPEE computers at Northumbria University. However we highly recommend you install Python on your own laptop or computer so that you can work from home, or from a cafe - wherever you work best! To install Python and the scientific libraries on your personal laptop or desktop carefully follow the instructions listed below. 

You can also run the Python Jupyter Notebook files remotely through the [binder](https://mybinder.org/) or [colab](https://colab.research.google.com) services whenever you see the icon for these services. But be warned! Any changes you make are not saved and the service can time-out after a period of inactivity (usually ~20 minutes). This service should be used as a if-nothing-else-works plan only.

You will also need a user account at [github.com](https://github.com) - Basic GitHub accounts are free.

### Python 

[Python](https://www.python.org/) is a popular language for scientific computing, and great for
general-purpose programming as well. Installing all of its scientific packages
individually can be a bit difficult, however, so we recommend the all-in-one
installer [Anaconda](https://www.anaconda.com/).

##### Windows - [video tutorial](https://www.youtube.com/watch?v=xxQ0mzZ8UvA)

1. Open [this link](https://www.anaconda.com/products/individual#download-section) with your web browser.

2. Download the Anaconda for Windows installer with Python 3. (If you are not sure which version to choose, you probably want the 64-bit Graphical Installer Anaconda3-...-Windows-x86_64.exe)

3. Double-click the executable and install Python 3 using _MOST_ of the
   default settings, the only exception is to check **Add Anaconda to my PATH environment variable**.

##### Mac OS X - [video tutorial](https://youtu.be/TcSAln46u9U)

1. Open [this link](https://www.anaconda.com/products/individual#download-section)
   with your web browser.

2. Download the Anaconda Installer with Python 3 for macOS (you can either use the Graphical or the Command Line Installer).

3. Install Python 3 by running the Anaconda Installer using all of the defaults for installation.
        
### A browser for Jupyter

We will teach Python using the [Jupyter notebook][https://jupyter.org/], a 
programming environment that runs in a web browser. Jupyter requires a reasonably 
up-to-date browser, preferably a current version of Chrome, Safari, or Firefox 
(note that Internet Explorer version 9 and below are *not* supported). Jupyter is installed as part of the Anaconda package for Python.

### How to launch a Jupyter Notebook

1. Search for "Anaconda" using your system search bar
2. Select "Anaconda Launcher"
3. Click on the "Launch" button below "Jupyter Notebook". You should see a file browser pop up as a new tab on your browser. 
4. Click `new` towards the top right hand side of the browser window. 
5. Select `Python 3` in the drop-down menu bar. This will open a Python 3 Notebook file a new tab in your browser.