---
title: "Introduction to Partial Differential Equations"
---

> It is a curious historical fact that modern quantum mechanics began with two quite different mathematical formulations: the differential equation of Schroedinger and the matrix algebra of Heisenberg. - Richard Feynman

In this section of the course we will learn how to solve another type of differential equation - the partial differential equation. These are also of vital importance to a physicist as they underly quantum mechanics (via the Schroedinger equation) and electromagnetism (via Maxwell's equations). They are also used to model heat diffusion and wave propagation, amongst other processes.

It is usually impossible to write down explicit formulas for solutions of partial differential equations, and so there is a vast amount of research dedicated to solving these equations using computers. In this lesson we will start to explore some of these numerical approaches, with a focus on understanding the underlying mathematical methods used rather than importing pre-made functions.

### Before you begin

- Check that Python and Jupyter Notebook are installed
- Launch a Jupyter notebook 

Please see the [Setup](../setup.qmd) page for more details.

### External resources

📖 Textbook: Mark Newman's Computational Physics section 5.10

{{< video https://youtu.be/ly4S0oi3Yz8 width="700" height="450" >}}

{{< video https://youtu.be/ToIXSwZ1pJU width="700" height="450" >}}
